namespace SyntheAudio
open Note
open Waves

module Song =
    
    // https://www.youtube.com/watch?v=eVTXPUF4Oz4
    let InTheEnd = [|
        // Intro
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F PHalfNote 4; // Reverb needed
        ADiese Triolet 3;
        ADiese HalfNote 3;
        B HalfNote 3;
        ADiese QuarterNote 3;

        // First Verse
        F White 5;
        ADiese PBlack 5;
        FDiese HalfNote 5;
        F White 5;
        DDiese Black 5;
        ADiese HalfNote 3;
        B Triolet 3;
        ADiese QuarterNote 3;
        F White 5;
        ADiese PBlack 5;
        FDiese HalfNote 5;
        F White 5;
        DDiese Black 5;
        ADiese HalfNote 3;
        B HalfNote 3;
        ADiese QuarterNote 3;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        F QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F PHalfNote 4;
        HalfSil HalfSilence 0;

        // Chorus
        ADiese Triolet 3;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese QuarterNote 4;
        F HalfNote 4;
        F Triolet 4;
        F Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        ADiese EightNote 3;
        CDiese EightNote 4;
        DDiese QuarterNote 4;
        F PHalfNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        DDiese Triolet 4;
        ADiese Triolet 3;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese QuarterNote 4;
        F HalfNote 4;
        F Triolet 4;
        F Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        ADiese EightNote 3;
        CDiese EightNote 4;
        DDiese QuarterNote 4;
        F PHalfNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        CDiese Triolet 4;
        DDiese EightNote 4;
        CDiese EightNote 4;
        ADiese EightNote 3;
        HalfSil HalfSilence 0;

        // Second Verse
        F White 5;
        ADiese PBlack 5;
        FDiese HalfNote 5;
        F White 5;
        DDiese Black 5;
        ADiese HalfNote 3;
        B Triolet 3;
        ADiese QuarterNote 3;
        F White 5;
        ADiese PBlack 5;
        FDiese HalfNote 5;
        F White 5;
        DDiese Black 5;
        ADiese HalfNote 3;
        B HalfNote 3;
        ADiese QuarterNote 3;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        F QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F HalfNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        DDiese HalfNote 4;
        ADiese HalfNote 4;
        ADiese HalfNote 4;
        FDiese HalfNote 4;
        F PHalfNote 4;
        HalfSil HalfSilence 0;

        // Chorus
        ADiese Triolet 3;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese QuarterNote 4;
        F HalfNote 4;
        F Triolet 4;
        F Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        ADiese EightNote 3;
        CDiese EightNote 4;
        DDiese QuarterNote 4;
        F PHalfNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        DDiese Triolet 4;
        HalfSil HalfSilence 0;
        ADiese Triolet 3;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese QuarterNote 4;
        F HalfNote 4;
        F Triolet 4;
        F Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        ADiese EightNote 3;
        CDiese EightNote 4;
        DDiese QuarterNote 4;
        F PHalfNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        CDiese Triolet 4;
        DDiese EightNote 4;
        CDiese EightNote 4;
        ADiese EightNote 3;
        HalfSil HalfSilence 0;

        // Third Verse
        FDiese Triolet 3;
        CDiese Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        FDiese PHalfNote 3;
        GDiese HalfNote 3;
        ADiese PHalfNote 3;
        CDiese Triolet 4;
        CDiese Triolet 4;
        CDiese HalfNote 4;
        FDiese HalfNote 3;
        FDiese HalfNote 3;
        ADiese HalfNote 3;
        GDiese PBlack 3;
        CDiese Triolet 4;
        CDiese Triolet 4;
        CDiese PHalfNote 4;
        FDiese HalfNote 3;
        FDiese HalfNote 3;
        FDiese HalfNote 3;
        ADiese HalfNote 3;
        GDiese HalfNote 3;
        FDiese HalfNote 3;
        ADiese HalfNote 3;
        GDiese PBlack 3;
        ADiese EightNote 3;
        GDiese EightNote 3;
        FDiese QuarterNote 3;
        HalfSil HalfSilence 0;
        ADiese Triolet 3;
        FDiese Triolet 4;
        FDiese HalfNote 4;
        FDiese PBlack 4;
        DDiese PHalfNote 4;
        F PBlack 4;
        FDiese Triolet 4;
        FDiese Triolet 4;
        FDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese HalfNote 4;
        FDiese HalfNote 4;
        FDiese PBlack 4;
        FDiese Triolet 4;
        FDiese Triolet 4;
        FDiese PHalfNote 4;
        DDiese HalfNote 4;
        DDiese Triolet 4;
        DDiese Triolet 4;
        FDiese HalfNote 4;
        F HalfNote 4;
        DDiese HalfNote 4;
        FDiese HalfNote 4;
        F PBlack 4;
        FDiese EightNote 4;
        F EightNote 4;
        DDiese Triolet 4;
        HalfSil HalfSilence 0;

        // Chorus
        ADiese Triolet 3;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese QuarterNote 4;
        F HalfNote 4;
        F Triolet 4;
        F Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        ADiese EightNote 3;
        CDiese EightNote 4;
        DDiese QuarterNote 4;
        F PHalfNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        DDiese Triolet 4;
        ADiese Triolet 3;
        CDiese HalfNote 4;
        DDiese HalfNote 4;
        DDiese QuarterNote 4;
        F HalfNote 4;
        F Triolet 4;
        F Triolet 4;
        CDiese HalfNote 4;
        CDiese PBlack 4;
        ADiese EightNote 3;
        CDiese EightNote 4;
        DDiese QuarterNote 4;
        F PHalfNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        F QuarterNote 4;
        FDiese QuarterNote 4;
        F QuarterNote 4;
        DDiese QuarterNote 4;
        CDiese Triolet 4;
        DDiese EightNote 4;
        CDiese EightNote 4;
        ADiese EightNote 3;
        HalfSil HalfSilence 0;

        // Outro
        DDiese PHalfNote 4;
        ADiese PHalfNote 4;
        ADiese PHalfNote 4;
        FDiese PHalfNote 4;
        F PHalfNote 4;
        F PHalfNote 4;
        F PHalfNote 4;
        F HalfNote 4;
        FDiese HalfNote 4;
        DDiese PHalfNote 4;
        ADiese PHalfNote 4;
        ADiese PHalfNote 4;
        FDiese PHalfNote 4;
        F PHalfNote 4;
        F PHalfNote 4;
        F PHalfNote 4;
        F HalfNote 4;
        FDiese HalfNote 4;
        DDiese PHalfNote 4;
        ADiese PHalfNote 4;
        ADiese PHalfNote 4;
        FDiese PHalfNote 4;
        F PHalfNote 4;
        F PHalfNote 4;
        F PHalfNote 4;
        F HalfNote 4;
        FDiese PBlack 4;
        DDiese HalfNote 4;
        FDiese HalfNote 4;
        ADiese HalfNote 4;
        DDiese HalfNote 5;
        F HalfNote 5;
        FDiese HalfNote 5;
        F PBlack 5;
        |]
    
    let GoldenWind =[|
        FDiese Black 5; 
        F White 5;
        D HalfNote 5;
        E HalfNote 5;
        F Black 5;
        E HalfNote 5;
        D HalfNote 5;
        CDiese HalfNote 5;
        D Black 5;
        E Black 5;
        FDiese White 5;
        B White 5;
        B HalfNote 4;
        CDiese HalfNote 5;
        D Black 5;
        E HalfNote 5;
        D HalfNote 5;
        CDiese HalfNote 5;
        A Black 5;
        G Black 5;
        FDiese Black 5; 
        F White 5;
        D HalfNote 5;
        E HalfNote 5;
        F HalfNote 5;
        E Black 5;
        D HalfNote 5;
        CDiese HalfNote 5;
        D HalfNote 5;
        E Black 5;
        FDiese Black 5;
        B White 5;
        B HalfNote 5;
        CDiese HalfNote 6;
        D HalfNote 6;
        G Black 5;
        FDiese HalfNote 5;
        F HalfNote 5;
        D Black 6;
        ADiese HalfNote 5;
        B White 5;
        |]

    let Lac = [|
        G Black 5
        Sil Silence 0
        DDiese Black 5
        G Black 5
        Sil Silence 0
        DDiese Black 5
        G Black 5
        Sil Silence 0
        DDiese Black 5
        GDiese Black 5
        ADiese Black 5
        F Black 5
        G Black 5
        Sil Silence 0
        DDiese Black 5
        G Black 5
        Sil Silence 0
        DDiese Black 5
        G Black 5
        Sil Silence 0
        DDiese Black 5
        GDiese Black 5
        ADiese Black 5
        F Black 5
        G Black 5
        Sil Silence 0
        C Black 5
        DDiese Black 5
        Sil Silence 0
        C Black 5
        DDiese Black 5
        Sil Silence 0
        C Black 5
        DDiese Black 5
        D Black 5
        DDiese Black 5
        F PWhite 5
        GDiese White 5
        F Black 5
        GDiese White 5
        F Black 5
        GDiese White 5
        F Black 5
        ADiese Black 5
        GDiese Black 5
        G Black 5
        GDiese White 5
        F Black 5
        GDiese White 5
        F Black 5
        GDiese White 5
        F Black 5
        ADiese Black 5
        GDiese Black 5
        G Black 5
        GDiese White 5
        F Black 5
        GDiese White 5
        F Black 5
        GDiese White 5
        F Black 5
        GDiese Black 5
        G Black 5
        GDiese Black 5
        ADiese PWhite 5
        ADiese PWhite 5

        G Black 5
        DDiese HalfNote 5
        G Black 5
        DDiese HalfNote 5
        G Black 5
        DDiese HalfNote 5
        GDiese HalfNote 5
        G HalfNote 5
        F HalfNote 5
        G Black 5
        DDiese HalfNote 5
        G Black 5
        DDiese HalfNote 5
        G Black 5
        DDiese HalfNote 5
        GDiese HalfNote 5
        G HalfNote 5
        F HalfNote 5
        |]

    let Solvieg =[|
        E White 5
        C HalfNote 5
        E HalfNote 5
        A HalfNote 5
        B HalfNote 5
        B HalfNote 5
        A HalfNote 5
        G Round 5
        G White 5
        E HalfNote 5
        G HalfNote 5
        C HalfNote 6
        D HalfNote 6
        B Black 5
        E White 6
        E HalfNote 6
        HalfSil HalfSilence 0 
        B Black 4
        E White 5
        E HalfNote 5
        Sil Silence 0
        MSil MSilence 0
        |]

    let Gadjet = [|
        G QuarterNote 5
        ADiese QuarterNote 5
        B QuarterNote 5
        CDiese QuarterNote 6
        DDiese HalfNote 6
        B HalfNote 5
        D HalfNote 6
        ADiese HalfNote 5
        CDiese HalfNote 6
        B HalfNote 5
        G QuarterNote 5
        ADiese QuarterNote 5
        B QuarterNote 5
        CDiese QuarterNote 6
        DDiese HalfNote 6
        GDiese HalfNote 6
        G White 6
        Sil Silence 0 
        E QuarterNote 6
        B QuarterNote 5
        B QuarterNote 5
        B QuarterNote 5
        E HalfNote 6
        B HalfNote 5
        D HalfNote 6
        ADiese HalfNote 5
        CDiese HalfNote 6
        B HalfNote 5
        Sil Silence 0 
        G QuarterNote 5
        ADiese QuarterNote 5
        B QuarterNote 5
        CDiese QuarterNote 6
        DDiese HalfNote 6
        B HalfNote 5
        D HalfNote 6
        ADiese HalfNote 5
        CDiese HalfNote 6
        B HalfNote 5
        G QuarterNote 5
        ADiese QuarterNote 5
        B QuarterNote 5
        CDiese QuarterNote 6
        DDiese HalfNote 6
        G HalfNote 6
        G White 6
        MSil Round 0 
        |]
        
    // Beginning of Unravel song 
    let Unravel = [|
        ADiese HalfNote 5
        C Black 6
        ADiese Black 5
        A HalfNote 5
        G Black 5
        C Black 6
        ADiese Black 5
        A Black 5
        G Black 5
        G HalfNote 5
        F PBlack 5
        DDiese PBlack 5
        DDiese Black 5
        F HalfNote 5
        D Black 5
        |]

    // La Vie En Rose, Edith Piaf
    let LVER = [|
        D PBlack 6
        CDiese HalfNote 6
        B PHalfNote 5
        A QuarterNote 5
        FDiese PHalfNote 5
        D QuarterNote 6
        CDiese PBlack 6
        B HalfNote 5
        A PHalfNote 5
        FDiese QuarterNote 5
        D PHalfNote 5
        CDiese QuarterNote 6
        B Black 5
        A Black 5
        B Black 5
        CDiese Black 6
        D Black 6
        B Black 5
        A HalfNote 5
        FDiese HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5
        D HalfNote 5
        CDiese HalfNote 5
        D HalfNote 5
        E HalfNote 5
        FDiese HalfNote 5
        G HalfNote 5
        G HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5
        DDiese HalfNote 5
        E HalfNote 5
        FDiese HalfNote 5
        G HalfNote 5
        A HalfNote 5
        A HalfNote 5
        G HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5
        FDiese HalfNote 5
        G HalfNote 5
        A HalfNote 5
        A HalfNote 5
        A HalfNote 5
        A HalfNote 5
        A HalfNote 5
        A HalfNote 5
        FDiese HalfNote 5
        GDiese HalfNote 5
        A White 5
        D PBlack 6
        CDiese HalfNote 6
        B PHalfNote 5
        A QuarterNote 5
        FDiese PHalfNote 5
        D QuarterNote 6
        CDiese PBlack 6
        B HalfNote 5
        A PHalfNote 5
        FDiese QuarterNote 5
        D PHalfNote 5
        CDiese QuarterNote 6
        B PBlack 5
        A HalfNote 5
        FDiese PHalfNote 5
        CDiese QuarterNote 5
        D PHalfNote 5
        CDiese QuarterNote 6
        B White 5
        A White 5
        |]

    let Kalinka = [|
        E Black 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 5;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        E HalfNote 6;
        E QuarterNote 6;
        E QuarterNote 6;
        D PHalfNote 6;
        C QuarterNote 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        E HalfNote 6;
        E HalfNote 6;

        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        E HalfNote 6;
        E QuarterNote 6;
        E QuarterNote 6;
        D HalfNote 6;
        C HalfNote 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        Sil Silence 0; 
        E HalfNote 6;
        G HalfNote 6;
        F HalfNote 6;
        E QuarterNote 6;
        D QuarterNote 6;

        C Black 6;
        G Black 5;
        E HalfNote 6;
        G HalfNote 5;
        F HalfNote 6;
        E QuarterNote 6;
        D QuarterNote 6;
        C Black 6;
        G Black 5;
        A Black 5;
        A HalfNote 5;
        B HalfNote 5;
        D HalfNote 6;
        C HalfNote 6;
        B HalfNote 5;
        A HalfNote 5;
        G Black 5;
        G Black 5;
        G White 5;
        E HalfNote 6;
        G HalfNote 5;
        F HalfNote 6;
        E QuarterNote 6;
        D QuarterNote 6;
        C Black 6;
        G Black 5;
        E HalfNote 6;
        G HalfNote 5;
        F HalfNote 6;
        E QuarterNote 6;
        D QuarterNote 6;

        C Black 6;
        G Black 5;
        A Black 5;
        A HalfNote 5;
        B HalfNote 5;
        D HalfNote 6;
        C HalfNote 6;
        B HalfNote 5;
        A HalfNote 5;
        G Black 5;
        F Black 6;
        E Black 6;
        E Black 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        E HalfNote 6;
        E QuarterNote 6;
        E QuarterNote 6;
        D PHalfNote 6;
        C QuarterNote 6;
        B HalfNote 5;
        C HalfNote 6;

        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        E HalfNote 6;
        E HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        E HalfNote 6;
        E QuarterNote 6;
        E QuarterNote 6;
        D PHalfNote 6;
        C QuarterNote 6;
        B HalfNote 5;
        C HalfNote 6;
        D Black 6;
        B HalfNote 5;
        C HalfNote 6;
        
        D Black 6;
        C HalfNote 6;
        B HalfNote 5;
        A Black 5;
        Sil Silence 0;
        |]

    let RR =[|  // A finir
        F PBlack 4
        G PBlack 4
        C Black 4
        G PBlack 4
        A PBlack 4
        C Triolet 5
        ADiese Triolet 4
        A Triolet 4
        F PBlack 4
        G PBlack 4 
        C White 4
        Sil Silence 4
        C HalfNote 4
        C HalfNote 4
        D QuarterNote 4
        E HalfNote 4
        F QuarterNote 4
        F PBlack 4
        G PBlack 4
        C Black 4
        G PBlack 4
        A PBlack 4
        C Triolet 5
        ADiese Triolet 4
        A Triolet 4
        F PBlack 4
        G PBlack 4 
        C Black 4
        E HalfNote 4
        F HalfNote 4
        F Black 4
        Sil Silence 4
        F QuarterNote 4
        F HalfNote 4 
        F QuarterNote 4
        |]

    let Megalovania = [|  // A Finir
        D QuarterNote 4
        D QuarterNote 4 
        D HalfNote 5
        A HalfNote 4
        QSilence QuarterSilence 4
        GDiese QuarterNote 4
        QSilence QuarterSilence 4
        G QuarterNote 4
        QSilence QuarterSilence 4
        F HalfNote 4
        D QuarterNote 4
        F QuarterNote 4
        G QuarterNote 4

        C QuarterNote 4
        C QuarterNote 4 
        D HalfNote 5
        A HalfNote 4
        QSilence QuarterSilence 4
        GDiese QuarterNote 4
        QSilence QuarterSilence 4
        G QuarterNote 4
        QSilence QuarterSilence 4
        F HalfNote 4
        D QuarterNote 4
        F QuarterNote 4
        G QuarterNote 4

        B QuarterNote 3
        ADiese QuarterNote 3 
        D HalfNote 5
        A HalfNote 4
        QSilence QuarterSilence 4
        GDiese QuarterNote 4
        QSilence QuarterSilence 4
        G QuarterNote 4
        QSilence QuarterSilence 4
        F HalfNote 4
        D QuarterNote 4
        F QuarterNote 4
        G QuarterNote 4

        ADiese QuarterNote 3
        ADiese QuarterNote 3 
        D HalfNote 5
        A HalfNote 4
        QSilence QuarterSilence 4
        GDiese QuarterNote 4
        QSilence QuarterSilence 4
        G QuarterNote 4
        QSilence QuarterSilence 4
        F HalfNote 4
        D QuarterNote 4
        F QuarterNote 4
        G QuarterNote 4
        |]

    let TOM = [|
        FDiese HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5
        B HalfNote 4
        HalfSil HalfSilence 0
        B HalfNote 4
        HalfSil HalfSilence 0
        E HalfNote 5
        HalfSil HalfSilence 0
        E HalfNote 5
        HalfSil HalfSilence 0
        E HalfNote 5
        GDiese HalfNote 5        
        GDiese HalfNote 5
        A HalfNote 5
        CDiese HalfNote 6
        A HalfNote 5        
        A HalfNote 5        
        A HalfNote 5
        E HalfNote 5
        HalfSil HalfSilence 0
        D HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        E HalfNote 5
        E HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5
        // Repeat
        FDiese HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5
        B HalfNote 4
        HalfSil HalfSilence 0
        B HalfNote 4
        HalfSil HalfSilence 0
        E HalfNote 5
        HalfSil HalfSilence 0
        E HalfNote 5
        HalfSil HalfSilence 0
        E HalfNote 5
        GDiese HalfNote 5        
        GDiese HalfNote 5
        A HalfNote 5
        CDiese HalfNote 6
        A HalfNote 5        
        A HalfNote 5        
        A HalfNote 5
        E HalfNote 5
        HalfSil HalfSilence 0
        D HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        E HalfNote 5
        E HalfNote 5
        FDiese HalfNote 5
        E HalfNote 5

        // Chorus
        D PBlack 5
        D HalfNote 5
        D HalfNote 5
        CDiese HalfNote 5
        B Black 4
        MSil MSilence 0
        CDiese HalfNote 5
        CDiese Black 5
        CDiese HalfNote 5
        CDiese HalfNote 5
        A HalfNote 4
        Sil Silence 0
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        FDiese Black 5
        E Black 5
        D PBlack 5
        D HalfNote 5
        D HalfNote 5
        CDiese Black 5
        B HalfNote 4
        B Black 4
        Sil Silence 0
        Sil Silence 0
        HalfSil HalfSilence 0
        E HalfNote 4
        CDiese Black 5
        CDiese HalfNote 5
        CDiese HalfNote 5
        CDiese HalfNote 5
        B HalfNote 4
        A HalfNote 4
        A HalfNote 4
        A HalfNote 4
        B HalfNote 4
        CDiese HalfNote 5
        B QuarterNote 4
        CDiese QuarterNote 5
        B HalfNote 4
        A Black 4
        Sil Silence 0
        D Black 5
        D Black 5
        D HalfNote 5
        E HalfNote 5
        E Black 5
        Sil Silence 0
        MSil MSilence 0
        Sil Silence 0
        FDiese HalfNote 4
        A HalfNote 4
        A HalfNote 4
        A HalfNote 4
        A HalfNote 4
        A HalfNote 4
        A HalfNote 4
        GDiese PBlack 4
        GDiese HalfNote 4
        FDiese PBlack 4
        A Round 4
        GDiese Round 4
        A Round 4
        E Black 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        FDiese Black 5
        E Black 5
        A Round 4
        E Round 5
        FDiese Round 5
        E Black 5
        HalfSil HalfSilence 0
        FDiese HalfNote 5
        FDiese Black 5
        E Black 5
        |]

    let ZeldaOverworld = [|
        A White 5
        A Triolet 5
        A Triolet 5
        A Triolet 5
        A Triolet 5
        A HalfNote 5
        G Triolet 5
        A Black 5
        TrSilence TrioletSilence 5
        TrSilence TrioletSilence 5
        A Triolet 5
        A Triolet 5
        A Triolet 5
        A Triolet 5
        A HalfNote 5
        G Triolet 5
        A Black 5
        TrSilence TrioletSilence 5
        TrSilence TrioletSilence 5
        A Triolet 5
        A Triolet 5
        A Triolet 5
        A Triolet 5
        A HalfNote 5
        E QuarterNote 5
        E QuarterNote 5
        E HalfNote 5
        E QuarterNote 5
        E QuarterNote 5
        E HalfNote 5
        E QuarterNote 5
        E QuarterNote 5
        E HalfNote 5
        E HalfNote 5
        |]
    
    let Crazy = [|
        D Black 5
        Sil Silence 0
        F Black 5
        HalfSil HalfSilence 0
        D HalfNote 5
        HalfSil HalfSilence 0
        D HalfNote 5
        G Black 5
        D Black 5
        C Black 5
        D Black 5
        Sil Silence 0
        A Black 5
        HalfSil HalfSilence 0
        D HalfNote 5
        HalfSil HalfSilence 0
        D HalfNote 5
        ADiese Black 5
        A Black 5
        F Black 5
        D Black 5
        A Black 5
        D Black 6
        D HalfNote 5
        C HalfNote 5
        HalfSil HalfSilence 0
        C HalfNote 5
        A Black 4
        E Black 5
        D Black 5
        Sil Silence 0
        D HalfNote 5
        HalfSil HalfSilence 0
        D Black 5
        D HalfNote 5
        C HalfNote 5
        HalfSil HalfSilence 0
        C HalfNote 5 
        HalfSil HalfSilence 0
        C HalfNote 5
        A Black 4
        C Black 5
        Sil Silence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        C HalfNote 6
        HalfSil HalfSilence 0
        C HalfNote 6
        HalfSil HalfSilence 0
        C HalfNote 6
        B HalfNote 5
        HalfSil HalfSilence 0
        B HalfNote 5
        HalfSil HalfSilence 0
        Sil Silence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        C HalfNote 6
        HalfSil HalfSilence 0
        C HalfNote 6
        B HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        Sil Silence 0
        Sil Silence 0
        F HalfNote 5
        HalfSil HalfSilence 0
        F HalfNote 5
        HalfSil HalfSilence 0
        F HalfNote 5
        HalfSil HalfSilence 0
        F HalfNote 5
        G HalfNote 5
        HalfSil HalfSilence 0
        G HalfNote 5
        HalfSil HalfSilence 0
        G HalfNote 5
        G Black 5
        G Black 5
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        HalfSil HalfSilence 0
        G HalfNote 5
        A HalfNote 5
        HalfSil HalfSilence 0
        A HalfNote 5
        A White 5
        |]

    let test (song: byte [][] ) =  // The most unbelievable thing to play a song
            let mutable wave2 = sinbyte 1. 0.
            for j in 0..song.Length-1 do
                let delay = Array.init (int(sampleRate/1000.)) (fun i -> 0. |> sample)
                wave2 <- Array.concat[|wave2; delay; song.[j]|]
            wave2
